### PR TITLE
Fix capitilisation in titles & paragraph margins/line breaks

### PR DESCRIPTION
**Pull request by posercorpse**
Titles were being messed with, "FOO" would become "Foo" with only the initial character capitalised.
Hope I'm doing this correctly, never done a pull request before

### CODE REVIEW

**Comment by posercorpse** [comment]
Also made a change to fix paragraph margins / line breaks

**Comment by Yarden-zamir** [comment]
Do you have a link to a deployment with the changes? It looks good but I don't have time to test it right now

**Review by Yarden-zamir — APPROVED** [review]

**Comment by posercorpse** [comment]
https://longpig.site/docs/home/

**Comment by Yarden-zamir** [comment]
Cool, merging

**Pull request merged**
